export const shoppingItems = [
  {
    category: "Fruits and Vegetables",
    name: "Avacado",
    note: "",
    quantity: 1,
  },
  {
    category: "Fruits and Vegetables",
    name: "Banana",
    note: "",
    quantity: 1,
  },
  {
    category: "Fruits and Vegetables",
    name: "Bunch of carrots 5pcs",
    note: "",
    quantity: 1,
  },
  {
    category: "Fruits and Vegetables",
    name: "Mandarin Nadorcott",
    note: "",
    quantity: 1,
  },
  {
    category: "Fruits and Vegetables",
    name: "Piele De Sapo Melon",
    note: "",
    quantity: 1,
  },
  {
    category: "Fruits and Vegetables",
    name: "Watermelon",
    note: "",
    quantity: 1,
  },
  {
    category: "Fruits and Vegetables",
    name: "Broccli",
    note: "",
    quantity: 1,
  },
  {
    category: "Fruits and Vegetables",
    name: "Oranges",
    note: "",
    quantity: 1,
  },
  {
    category: "Fruits and Vegetables",
    name: "Grapes",
    note: "",
    quantity: 1,
  },
  {
    category: "Meat and Fish",
    name: "Chicken leg box",
    note: "",
    quantity: 1,
  },
  {
    category: "Meat and Fish",
    name: "Chicken 1kg",
    note: "",
    quantity: 1,
  },
  {
    category: "Meat and Fish",
    name: "Pork fillets 450g",
    note: "",
    quantity: 1,
  },
  {
    category: "Meat and Fish",
    name: "Salmon 1kg",
    note: "",
    quantity: 1,
  },
  {
    category: "Meat and Fish",
    name: "Sirloin Steak",
    note: "",
    quantity: 1,
  },
  {
    category: "Meat and Fish",
    name: "New York strip steak",
    note: "",
    quantity: 1,
  },
  {
    category: "Meat and Fish",
    name: "Ribeye steak",
    note: "",
    quantity: 1,
  },
  {
    category: "Meat and Fish",
    name: "Tuna fish",
    note: "",
    quantity: 1,
  },
  {
    category: "Beverages",
    name: "Sprite 2 liter",
    note: "",
    quantity: 1,
  },
  {
    category: "Beverages",
    name: "Truly 12 pack",
    note: "",
    quantity: 1,
  },
  {
    category: "Beverages",
    name: "Coke Zero 2 liter",
    note: "",
    quantity: 1,
  },
  {
    category: "Beverages",
    name: "Lemonade 2 liter carton",
    note: "",
    quantity: 1,
  },
  {
    category: "Beverages",
    name: "Gatorade 8 pack",
    note: "",
    quantity: 1,
  },
  {
    category: "Beverages",
    name: "Hi C fruit punch",
    note: "",
    quantity: 1,
  },
  {
    category: "Beverages",
    name: "Capris Sun 24 pack",
    note: "",
    quantity: 1,
  },
];
